improve for release

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -42,15 +42,15 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Download previous blockmap (optional)
-        run: curl -fL "https://github.com/jakeyizle/melee-dex/releases/download/v${{ env.previous_version }}/melee-dex_${{ env.previous_version }}.exe.blockmap" -o "release/${{ steps.vars.outputs.version }}/melee-dex_${{ env.previous_version }}.exe.blockmap" || echo "Previous blockmap not found, continuing without it."
+        run: curl -fL "https://github.com/jakeyizle/melee-dex/releases/download/v${{ env.previous_version }}/MeleeDex_${{ env.previous_version }}.exe.blockmap" -o "release/${{ steps.vars.outputs.version }}/MeleeDex_${{ env.previous_version }}.exe.blockmap" || echo "Previous blockmap not found, continuing without it."
 
       - name: Upload to GitHub Release
         uses: softprops/action-gh-release@v2
         with:
           files: |
-            release/${{ steps.vars.outputs.version }}/melee-dex_${{ steps.vars.outputs.version }}.exe
-            release/${{ steps.vars.outputs.version }}/melee-dex_${{ steps.vars.outputs.version }}.exe.blockmap
+            release/${{ steps.vars.outputs.version }}/MeleeDex_${{ steps.vars.outputs.version }}.exe
+            release/${{ steps.vars.outputs.version }}/MeleeDex_${{ steps.vars.outputs.version }}.exe.blockmap
             release/${{ steps.vars.outputs.version }}/latest.yml
-            release/${{ steps.vars.outputs.version }}/melee-dex_${{ env.previous_version }}.exe.blockmap
+            release/${{ steps.vars.outputs.version }}/MeleeDex_${{ env.previous_version }}.exe.blockmap
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
